project:
  type: book

execute:
  enabled: false

book:
  title: "cyllama user guide"
  author: "S. Alireza"
  date: "12/01/2025"
  version: "0.1.18"
  chapters:
    - index.qmd
    - intro.qmd
    - src/quickstart.qmd
    - src/installation.qmd
    - src/overview.qmd
    - summary.qmd
    - part: "Llama.cpp"
      chapters:
      - src/user_guide.qmd
      - src/cookbook.qmd
      - src/examples.qmd
      - src/build_backends.qmd
      - src/context_caching.qmd
      - src/server_usage_examples.qmd
    - part: "Whisper.cpp"
      chapters:
      - src/whisper.qmd
    - part: "Stable-Diffusion.cpp"
      chapters:
      - src/stable_diffusion.qmd
    - part: "Agents"
      chapters:
      - src/agents_overview.qmd
    - part: "RAG Support"
      chapters:
      - src/rag_overview.qmd
      - src/rag_embedder.qmd
      - src/rag_vectorstore.qmd
      - src/rag_text_processing.qmd
      - src/rag_pipeline.qmd
      - src/rag_advanced.qmd
  appendices:
    - src/api_reference.qmd
    - src/troubleshooting.qmd
    

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



